name: build armbian CI

env:
  REPO_URL: https://github.com/armbian/build 
on:
  workflow_dispatch:
    inputs:
      REPO_BRANCH:
        description: "Select Sources Branch "
        required: false
        default: "main"
        type: choice
        options:
          - main
          - v24.2.1
          - v23.11.2
          - v23.11
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout - clone repository
      uses: actions/checkout@main

    - name: Download - openwrt source download
      run: |
        git clone --depth=1 --branch=${{ inputs.REPO_BRANCH }}  $REPO_URL
  
    - name: Build - build armbian
      working-directory: build
      run: |
        ./compile.sh PREFER_DOCKER=no BOARD=aml-s9xx-box BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=bookworm

    - name: Compress - compress image
      working-directory: build/output/images
      run: |
        sudo xz -T 0 *.img
        
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@main
      with:
        name: armbian
        path: |
           build/output/images/*




